export type SelectOption = {
  value: string;
  label: string;
};

export const ORGANIZATION_COUNTRY_OPTIONS: SelectOption[] = [
  { value: "", label: "Selecciona un pais" },
  { value: "AR", label: "AR - Argentina" },
  { value: "BO", label: "BO - Bolivia" },
  { value: "BR", label: "BR - Brasil" },
  { value: "CA", label: "CA - Canada" },
  { value: "CH", label: "CH - Suiza" },
  { value: "CL", label: "CL - Chile" },
  { value: "CN", label: "CN - China" },
  { value: "CO", label: "CO - Colombia" },
  { value: "CR", label: "CR - Costa Rica" },
  { value: "DE", label: "DE - Alemania" },
  { value: "DO", label: "DO - Republica Dominicana" },
  { value: "EC", label: "EC - Ecuador" },
  { value: "ES", label: "ES - Espana" },
  { value: "FR", label: "FR - Francia" },
  { value: "GB", label: "GB - Reino Unido" },
  { value: "GT", label: "GT - Guatemala" },
  { value: "HN", label: "HN - Honduras" },
  { value: "IT", label: "IT - Italia" },
  { value: "JP", label: "JP - Japon" },
  { value: "MX", label: "MX - Mexico" },
  { value: "NI", label: "NI - Nicaragua" },
  { value: "PA", label: "PA - Panama" },
  { value: "PE", label: "PE - Peru" },
  { value: "PT", label: "PT - Portugal" },
  { value: "PY", label: "PY - Paraguay" },
  { value: "US", label: "US - Estados Unidos" },
  { value: "UY", label: "UY - Uruguay" },
  { value: "VE", label: "VE - Venezuela" },
];

export const ORGANIZATION_CURRENCY_OPTIONS: SelectOption[] = [
  { value: "", label: "Selecciona una moneda" },
  { value: "ARS", label: "ARS - Argentine Peso" },
  { value: "BOB", label: "BOB - Bolivian Boliviano" },
  { value: "BRL", label: "BRL - Brazilian Real" },
  { value: "CAD", label: "CAD - Canadian Dollar" },
  { value: "CHF", label: "CHF - Swiss Franc" },
  { value: "CLP", label: "CLP - Chilean Peso" },
  { value: "CNY", label: "CNY - Chinese Yuan" },
  { value: "COP", label: "COP - Colombian Peso" },
  { value: "CRC", label: "CRC - Costa Rican Colon" },
  { value: "DOP", label: "DOP - Dominican Peso" },
  { value: "EUR", label: "EUR - Euro" },
  { value: "GBP", label: "GBP - British Pound" },
  { value: "GTQ", label: "GTQ - Guatemalan Quetzal" },
  { value: "HNL", label: "HNL - Honduran Lempira" },
  { value: "JPY", label: "JPY - Japanese Yen" },
  { value: "MXN", label: "MXN - Mexican Peso" },
  { value: "NIO", label: "NIO - Nicaraguan Cordoba" },
  { value: "PAB", label: "PAB - Panamanian Balboa" },
  { value: "PEN", label: "PEN - Peruvian Sol" },
  { value: "PYG", label: "PYG - Paraguayan Guarani" },
  { value: "USD", label: "USD - US Dollar" },
  { value: "UYU", label: "UYU - Uruguayan Peso" },
  { value: "VES", label: "VES - Venezuelan Bolivar" },
];
